name: React Native CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: List all files in repository (for debugging)
        run: /bin/ls -la

      - name: Navigate to the APP/leitura-no-vagao directory and install dependencies
        run: |
          cd APP/leitura-no-vagao
          /bin/ls -la
          npm install

      - name: Run tests
        run: |
          cd APP/leitura-no-vagao
          bash -c "npm test" || echo "Falha ao executar os testes!"
